pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Maven Setup') {
            steps {
                sh 'export M2_HOME=/opt/apache-maven-3.9.9'
                sh 'export M2=/opt/apache-maven-3.9.9/bin'
                sh 'export PATH=/opt/apache-maven-3.9.9/bin/:$PATH'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -version'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
